<p>test9 values the privacy of our visitors/customers and takes every  known precaution to safe guard the information we collect from  unauthorized use.We take that trust seriously, and, as a result, we seek  to ensure the security of your personal information online. This  privacy policy is an effort to answer your privacy-related questions. If  you have questions that are not addressed herein, please submit them to  us by sending an email to&nbsp; <a href="mailto:order@fpvok.com">order@fpvok.com</a>.</p>
<p>To assist you with your review of our Policy, we have provided answers to questions that you may find important:</p>
<p><strong>What Personal Information We Collect? </strong></p>
<p>test9 collects personally identifiable information that you  specifically and voluntarily provide on the Site or by email to test9. Personally identifiable information ("PII") is information  that identifies you as a specific individual, for example, your name,  company name, account number, physical or email address, and phone  number plus other information that personally identifies you including  your industry, the number of employees at your company, and purchase  history. The Site includes both public areas, open to all visitors, and  private areas that are open only to those visitors who choose to  register. In addition, visitors can sign up on the Site to request email  newsletters and other information from test9. test9 collects PII  from you when you:&nbsp; <br /> &nbsp;<br /> Make a purchase <br /> Create an account <br /> Subscribe to our newsletter <br /> Request a catalog via email or our website <br /> Participate in a survey <br /> Register at our website&nbsp;</p>
<p><strong>How We Use the Personal Information We Collect? </strong></p>
<p>We use the PII that you provide to us in order to 1) fulfill requests  for products, services and/or information, 2) provide customer service,  3) offer new products or services, 4) measure and improve the  effectiveness of our Site and our marketing endeavors, 5) tailor our  online offerings to your preferences, 6) administer promotions or  surveys, and 7) achieve other business purposes as permitted under  applicable law.&nbsp;</p>
<p><strong>How We Protect Your Personal Information? </strong></p>
<p>To help ensure the security of your PII, onSale seeks to use security  technology and procedures, which are reviewed periodically. We use  encryption technology and Secure Socket Layers ("SSL") in all areas  where your personal and account information is required. This means that  the PII you submit to us via our Site is encrypted by your computer,  and then decrypted again on our side, discouraging others from accessing  your private information during transmission. If your browser does not  support SSL or if you are unable to establish a secure connection due to  a company firewall, please email us at <a href="mailto:order@fpvok.com">order@fpvok.com</a> to place your order via email.</p>
<p>In addition, your personal, account information, and transaction history are kept behind our firewall.&nbsp;</p>
<p><strong>Can I Correct Or Remove Information From Your Site?</strong></p>
<p>You always have the option to view your account to make sure the  information we have collected from you is indeed correct. You also have  the option of removing any information from your account that you wish  to keep private. However, please note that removing certain information  such as your email address, contact information, and the like may  greatly hinder our ability to effectively provide the service or  products you have requested. We recommend, that you contact us first to  discuss which information you may remove without interrupting the  quality of service we intend to provide for you.<br /> &nbsp;<br /> <strong>Can I Opt-out Of Having Certain Information Collected?</strong></p>
<p>You have the option of disabling your computers ability to accept or  transmit cookies. This will prevent us from gathering certain  non-personally identifiable information from you. You also have the  option of removing yourself from any email distribution list that you  may have signed up for.</p>
<p><strong>Notice Of Changes To This Privacy Policy.</strong></p>
<p>We reserve the right to change this privacy policy at any time.  However, if any changes do occur, we will publish the changes to our web  site and post a notice on the home page that a new privacy policy has  been implemented. We will also take reasonable steps to contact you  personally to let you know of the new changes. Should the company be  bought or sold to someone else, we will take reasonable steps to notify  you personally. You will then be given the option to keep your account  open or to terminate.</p>
<hr />
<p><span style="font-size: small;"><em><span style="font-family: arial,helvetica,sans-serif;"><span class="fl">Visit a Part of Categories of www.fpvok.com</span></span></em></span></p>
<p><span style="font-size: small;"><em><span style="font-family: arial,helvetica,sans-serif;">:</span></em></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="http://www.fpvok.com/Wholesale-xboxxbox360_c401.html">Xbox360 accessories</a><span>&nbsp; |&nbsp; </span><a href="http://www.fpvok.com/Wholesale-nintendo-wii_c726.html">Nintendo Wii Accessories</a><br /></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="http://www.fpvok.com/Wholesale-sony-ps3_c749.html">Sony PS3 Accessories</a>&nbsp; |&nbsp; <a href="http://www.fpvok.com/Wholesale-nintendo-3ds_c723.html">Nintendo 3DS Accessories</a></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="http://www.fpvok.com/Wholesale-psp-go_c394.html">PSP Go Accessories</a>&nbsp; |&nbsp; <a href="http://www.fpvok.com/Wholesale-psp-3000_c397.html">PSP3000 Accessories</a><a title="IBM,Acer,Lenovo,ASUS Laptop Battery,Charger,PC Web Cameras,USB Fan,USB Light,Memory Card &amp; Reader" href="/Wholesale-computer-accessories_c1100.html" target="_blank"> </a></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="http://www.fpvok.com/Wholesale-ipadiphone_c393.html">iPad &amp; iPhone Accessories</a> &nbsp; |&nbsp;&nbsp; <a href="http://www.fpvok.com/Wholesale-ndsi-llxl_c724.html">Nintendo DSi LL/XL Accessories</a><a title="Apple iPad,iPod,iPhone,iPhone 3G,iPhone 3GS,iPhone 4 Accessories - Case, Cover,Earphone,Cable,Charger,Touch Stylus" href="/Wholesale-computer-accessories-ipad-accessories_c1133.html" target="_blank"> </a></span></p>