<div class="BlockContent">
<div class="middle">
<p style="text-align: justify;"><span style="font-family: arial;"><strong>Content of Website</strong><br /><br />Although www.fpvok.com  updates and publishes content on this site in good faith, no  representation is made concerning the completeness or accuracy of the  information contained herein. Certain parts of the website may be  incomplete, contain errors or become expired at any point in  time.&nbsp;Joyobuy expressly disclaims and makes no commitment to update any  of the content on this website. test9 reserves the right to add,  modify or delete any information on the website at any point in time</span></p>
<p><span><br /></span></p>
<p style="text-align: justify;"><span style="font-family: arial;"><strong>Restrictions On Use</strong><br /><br />All  users agree to abide and adhere to all applicable local, provincial,  federal and international laws and regulations when using Joyobuy. All  users agree to not use test9 in a means that may be a violation of  third party rights, including intellectual property rights. All users  will not use test9 for illegal purposes. test9 will not be held  responsible or liable for any kind of damages that arise from  the test9 website by improper use. This will include, but is not  limited to, direct, indirect, punitive, incidental and consequential  damages</span></p>
<p><span><br /></span></p>
<p><span style="font-family: arial;"><strong>Returns</strong><br /><br />We  are confident that you will be delighted with your product and our  service but if you find it necessary to return a defective item, we have  an efficient process to expedite your return request<br /><br />You can  return any defective product within 14 days after the invoice date. We  will not accept any return after 14 days from the purchased date. <strong>Any  product returned must be in resalable condition. Products returned to  us in not resalable condition will not be accepted and will be returned  to you at your expense</strong><br /><br />You are responsible for all  shipping costs when returning item(s) to us. We will incur all shipping  fees for any defective item(s) replaced. This applies to all returns  without exception<br /><br /><strong>We will not accept any goods returned due to purchaser error or returned products evaluated not to be faulty.</strong> We reserve the right to determine whether or not a product is defective. This applies to all sales without exception</span></p>
<p><span><br /></span></p>
<p style="text-align: justify;"><span style="font-family: arial;"><span><strong>If the returned product is verified faulty:</strong><br />The  product will be replaced or repaired as soon as possible. If the item  is out of stock or no longer available, it will be replaced with an  equivalent specification product&nbsp; </span></span></p>
<p style="text-align: justify;"><span style="font-family: arial;"><span><strong>If the returned product is verified as working:</strong><br />The  product will be shipped back to you as soon as possible. In this case,  the customer is responsible for all return shipping costs which can be  paid by credit card or bank transfer</span><span style="color: #ff0000;"><strong><br /> </strong></span></span></p>
<p style="text-align: justify;"><span style="font-family: arial;"><strong><span>Any item that is verified as working, and has been soldered upon is NOT eligible for return<br /> </span></strong></span></p>
<p style="text-align: justify;"><span style="font-family: arial;"><strong><span>Any item that is in not resalable condition for another reason is NOT eligible for return. No exceptions to this whatsoever </span></strong></span></p>
</div>
</div>
<p><span><span style="font-family: arial,helvetica,sans-serif;"><br /><strong>www.fpvok.com Management.</strong></span></span></p>
<hr />
<p><span style="font-size: small;"><em><span style="font-family: arial,helvetica,sans-serif;"><span class="fl">Visit a Part of Categories of www.fpvok.com</span></span></em></span></p>
<p><span style="font-size: small;"><em><span style="font-family: arial,helvetica,sans-serif;">:</span></em></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="/Wholesale-xboxxbox360_c401.html">Xbox360 accessories</a><span>&nbsp; |&nbsp; </span><a href="/Wholesale-nintendo-wii_c726.html">Nintendo Wii Accessories</a><br /></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="/Wholesale-sony-ps3_c749.html">Sony PS3 Accessories</a>&nbsp; |&nbsp; <a href="/Wholesale-nintendo-3ds_c723.html">Nintendo 3DS Accessories</a></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="/Wholesale-psp-go_c394.html">PSP Go Accessories</a>&nbsp; |&nbsp; <a href="/Wholesale-psp-3000_c397.html">PSP3000 Accessories</a><a title="IBM,Acer,Lenovo,ASUS Laptop Battery,Charger,PC Web Cameras,USB Fan,USB Light,Memory Card &amp; Reader" href="/Wholesale-computer-accessories_c1100.html" target="_blank"> </a></span></p>
<p><span style="font-size: xx-small; color: #333333;"><a href="/Wholesale-ipadiphone_c393.html">iPad &amp; iPhone Accessories</a> &nbsp; |&nbsp;&nbsp; <a href="/Wholesale-ndsi-llxl_c724.html">Nintendo DSi LL/XL Accessories</a></span></p>