try{document.domain=window.location.hostname.split('.').reverse().slice(0,2).reverse().join('.');}catch(e){}
$(document).ready(function(){if(!$.browser.msie){$('form,select,input').attr('autocomplete','off');}
if($('.search .search-input input').val()==''){$('.search .search-input input').addClass('empty');}
$('.search .search-input input').focus(function(){$('.search .search-input input').removeClass('empty');}).blur(function(){if($(this).val()==''){$(this).addClass('empty');}});$('.search .search-select, .search .search-select input').click(function(){setTimeout(function(){$('.search .search-category').show();},100);});$(document).click(function(){$('.search .search-category').hide();});$('.search .search-category a').click(function(){setTimeout(function(){$('.search .search-category').hide();},200);$('#search-cid').val($(this).attr('rel'));$('.search .search-select input').val($(this).html());});$('#header-menu li[rel=menu]').mouseover(function(){$(this).addClass('active').find('.sub-category').show();$('.search .search-category').hide();if($.browser.msie&&$.browser.version!='8.0'){$('#header-menu').css('z-index',80);}}).mouseout(function(){$(this).removeClass('active').find('.sub-category').hide();if($.browser.msie&&$.browser.version!='8.0'){$('#header-menu').css('z-index','');}});$('.index-tab-frame .left li').click(function(){$(this).parents('ul').find('li').removeClass('active');$(this).addClass('active');});$('#email-sub-btn').click(function(){var submit=false;if(submit){return false;}
var email=$('#email-sub').val();if(!isEmail(email)){alert('Email address error');return false;}
submit=true;$.ajax({url:AccountUrl+'other/emailsub.do?rand='+Math.random(),type:'POST',xhr:AjaxProxy,data:{'email':email},success:function(info){if(info=='200'){var ok=$('#tpl_edm_ok').html().replace(/-_-/ig,'').format(email);ok=$(ok);ok.find('.close-window').click(function(){UnDialog();});Dialog(ok);submit=false;}else{alert(info);submit=false;}},error:function(info){alert('Network errors,please try again');submit=false;}});});$(".text-cols-box .max .left").jCarouselLite({auto:false,circular:false,visible:1,btnNext:".text-cols-box .max .right .next",btnPrev:".text-cols-box .max .right .prev",btnPrevDisableClass:'prev-disable',btnNextDisableClass:'next-disable'});$('#header-menu ul li.currency .list').html('<a href="{0}other/currency.do?code=EUR"><img src="/images/currency/EUR.gif" align="absmiddle"> Euro</a><a href="{0}other/currency.do?code=GBP"><img src="/images/currency/GBP.gif" align="absmiddle"> GB Pound</a><a href="{0}other/currency.do?code=AUD"><img src="/images/currency/AUD.gif" align="absmiddle"> Australian Dollar</a><a href="{0}other/currency.do?code=CAD"><img src="/images/currency/CAD.gif" align="absmiddle"> Canadian Dollar</a><a href="{0}other/currency.do?code=HKD"><img src="/images/currency/HKD.gif" align="absmiddle"> Hong Kong Dollars</a><a href="{0}other/currency.do?code=USD"><img src="/images/currency/USD.gif" align="absmiddle"> US Dollar</a>'.format(AccountUrl));$('.#header-menu ul li.currency').mouseover(function(){$(this).addClass('currency_on');$(this).find('.list').show();});$('.#header-menu ul li.currency').mouseout(function(){$(this).removeClass('currency_on');$(this).find('.list').hide();});$('.currency-box div').html('<a href="{0}other/currency.do?code=EUR"><img src="/images/currency/EUR.gif" align="absmiddle"> Euro</a><a href="{0}other/currency.do?code=GBP"><img src="/images/currency/GBP.gif" align="absmiddle"> GB Pound</a><a href="{0}other/currency.do?code=AUD"><img src="/images/currency/AUD.gif" align="absmiddle"> Australian Dollar</a><a href="{0}other/currency.do?code=CAD"><img src="/images/currency/CAD.gif" align="absmiddle"> Canadian Dollar</a><a href="{0}other/currency.do?code=HKD"><img src="/images/currency/HKD.gif" align="absmiddle"> Hong Kong Dollars</a><a href="{0}other/currency.do?code=USD"><img src="/images/currency/USD.gif" align="absmiddle"> US Dollar</a>'.format(AccountUrl));$('.currency-box').mouseover(function(){$(this).find('div').show();});$('.currency-box').mouseout(function(){$(this).find('div').hide();});$('.footer-mail-sub .text').focus(function(){$(this).removeClass('empty');}).blur(function(){if($(this).val()==''){$(this).addClass('empty');}});if(typeof(NoGoToTop)=='undefined'){$('body').append('<div id="gototop"></div>');$('#gototop').css("left",Math.floor(($(window).width()-960)/2)+960+15+"px");if($.browser.msie&&$.browser.version=='6.0'){$('#gototop').css("position","absolute");}
else{$('#gototop').css("top",$(window).height()-200+"px");}
$(window).scroll(function(){if($(this).scrollTop()>100){$('#gototop').fadeIn();}else{$('#gototop').fadeOut();}});$('#gototop').click(function(){$('body,html').animate({scrollTop:0},800);return false;});}
function RandString(l){var x="123456789poiuytrewqasdfghjklmnbvcxzQWERTYUIPLKJHGFDSAZXCVBNM";var tmp="";for(var i=0;i<l;i++){tmp+=x.charAt(Math.ceil(Math.random()*100000000)%x.length);}
return tmp;}
if(!$.cookie('mw_v')){$.cookie('mw_v',RandString(32),{expires:365,path:'/',domain:Domain});}
if($.cookie('k2_sid')){if(!$.cookie('mw_u')){$.cookie('mw_u',$.cookie('k2_sid'),{expires:365,path:'/',domain:Domain});}else{if($.cookie('mw_u')!=$.cookie('k2_sid')){$.cookie('mw_u',$.cookie('k2_sid'),{expires:365,path:'/',domain:Domain});}}}else{$.cookie('mw_u',null);}
$.cookie('mw_lpt',Date.parse(new Date()),{expires:365,path:'/',domain:Domain});var theNew=0;var lastVisitTime=$.cookie('mw_lvt')?$.cookie('mw_lvt'):0;var lastPageTime=$.cookie('mw_lpt')?$.cookie('mw_lpt'):0;if(Date.parse(new Date())-lastPageTime>=1800){theNew=1;$.cookie('mw_lvt',Date.parse(new Date()),{expires:365,path:'/',domain:Domain});}
var gifUrl='';gifUrl+='http://a'+Domain+"/a.gif?r="+Math.random();gifUrl+="&referer="+(document.referrer?encodeURIComponent(document.referrer):'');gifUrl+="&time="+Date.parse(new Date());gifUrl+="&lvt="+lastVisitTime;gifUrl+="&new="+theNew;if(typeof(noAnalyticsGif)=='undefined'){$('body').append('<img src="'+gifUrl+'" width="1"/>');}});