<table id="table56" style="border: 1px solid #cecfce; margin-top: 10px;" border="0" cellspacing="0" cellpadding="0" width="735">
<tbody>
<tr>
<td width="25%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=1686" target="_blank"> <img src="/images/l/201103/a/12992993627.jpg" border="0" alt="7 inch 800*480 TFT LCD Touch Screen Google Android OS Tablet Laptop with VIA VM8505 533MHZ CPU + WIFI + Camera" width="128" height="128" /></a></td>
<td width="25%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=1685" target="_blank"> <img src="/images/l/201009/12853817130.jpg" border="0" alt="10.2 inch TFT LCD Touch Panel Google Android OS 2.1 Tablet PC with Dual Core 1GMHZ CPU + WIFI + 3G(2GB)" width="128" height="128" /></a></td>
<td width="25%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=1759" target="_blank"> <img src="/images/l/201011/b/12901323559.jpg" border="0" alt="10.1 Inch TFT LCD Touch Screen Google Android Tablet PC with VIA VM 8505 533MHZ CPU +2.0 MP Camera + WIFI + 3G(2GB)" width="128" height="128" /></a></td>
<td width="33%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=1724" target="_blank"> <img src="/images/l/201010/12868561710.jpg" border="0" alt="8 Inch TFT LCD Multi-touch Google Android OS Tablet PC RK2808 WIFI Camera ( 4500mAh Li-ion battery )" width="128" height="128" /></a></td>
</tr>
<tr>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" width="25%" align="middle"><span style="font-family: Arial;"><span style="font-size: 9pt;"> <a href="/index.php?main_page=product_info&amp;products_id=1686"> 7 inch 800*480 TFT LCD Touch Screen Google Android OS Tablet Laptop with VIA VM8505 533MHZ CPU + WIFI + Camera</a></span></span></td>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" width="25%" align="middle"><span style="font-family: Arial;"><span style="font-size: 9pt;"> <a href="/index.php?main_page=product_info&amp;products_id=1685"> 10.2 inch TFT LCD Touch Panel Google Android OS 2.1 Tablet PC with Dual Core 1GMHZ CPU + WIFI + 3G(2GB)</a></span></span></td>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" width="25%" align="middle"><span style="font-family: Arial;"> <a href="/index.php?main_page=product_info&amp;products_id=1759"> 10.1 Inch TFT LCD Touch Screen Google Android Tablet PC with VIA VM 8505 533MHZ CPU +2.0 MP Camera + WIFI + 3G(2GB)</a></span></td>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" align="middle"><span style="font-family: Arial;"><span style="font-size: 9pt;"> <a href="/index.php?main_page=product_info&amp;products_id=1724"> 8 Inch TFT LCD Multi-touch Google Android OS Tablet PC RK2808 WIFI Camera ( 4500mAh Li-ion battery )</a></span></span></td>
</tr>
<tr style="FONT: bold 12px Verdana, Arial, Helvetica, sans-serif; COLOR: #bf0000">
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" width="25%" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;"><span style="color: #800000;">Price: <span style="font-size: small;"><span style="font-size: x-small;"><span style="text-decoration: line-through;">US$87.65</span></span> <span style="color: #ff0000;">US$79.99</span></span></span> </span></strong></td>
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" width="25%" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;">Price: US$159.99</span></strong></td>
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" width="25%" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;">Price: US$149.98</span></strong></td>
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" height="22" align="center"><span style="color: #800000;"><strong><span style="font-size: small; font-family: Arial;">Price: <span style="font-size: x-small;"><span style="text-decoration: line-through;">US$159.60</span></span> <span style="color: #ff0000;">US$153.50</span><br /></span></strong></span></td>
</tr>
<tr>
<td width="25%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=1760" target="_blank"> <img src="/images/l/201011/b/12901368127.jpg" border="0" alt="10.2 inch Touch Panel Android OS 2.1 UMPC with FlyTouch CPU + WIFI + HDMI + GPS" width="128" height="128" /></a></td>
<td width="25%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=2527" target="_blank"> <img src="/images/l/201103/a/12994707575.jpg" border="0" alt="8 inch Touch Screen Android 2.2 VIA 8650 800MHZ Tablet PC with WIFI + 3G + Bluetooth" width="128" height="128" /></a></td>
<td width="25%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=1761" target="_blank"> <img src="/images/l/201011/b/12901407518.jpg" border="0" alt="8 Inch TFT LCD Google Android OS 2.2 Tablet PC - Freescale A8 1GHZ + Internal 4GB Memory" width="128" height="128" /></a></td>
<td width="33%" align="center"><a href="/index.php?main_page=product_info&amp;products_id=2184" target="_blank"> <img src="/images/l/201102/b/12989514419.jpg" border="0" alt="9.7 inch 1024*768 Capacitive Multi-Touch Screen Android 2.2 UMPC with Freescale Cortex A8 CPU + HDMI + 3G Support" width="128" height="128" /></a></td>
</tr>
<tr>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" width="25%" align="middle"><span style="font-family: Arial;"><span style="font-size: 9pt;"> <a href="/index.php?main_page=product_info&amp;products_id=1760"> 10.2 inch Touch Panel Android OS 2.1 UMPC with FlyTouch CPU + WIFI + HDMI + GPS</a></span></span></td>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" width="25%" align="middle"><span style="font-family: Arial;"><span style="font-size: 9pt;"> <a href="/index.php?main_page=product_info&amp;products_id=2527"> 8 inch Touch Screen Android 2.2 VIA 8650 800MHZ Tablet PC with WIFI + 3G + Bluetooth </a></span></span></td>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" width="25%" align="middle"><span style="font-family: Arial;"> <a href="/index.php?main_page=product_info&amp;products_id=1761"> 8 Inch TFT LCD Google Android OS 2.2 Tablet PC - Freescale A8 1GHZ + Internal 4GB Memory</a></span></td>
<td style="BORDER-RIGHT: #dbdcdb 1px solid; PADDING-RIGHT: 20px; PADDING-LEFT: 20px; PADDING-BOTTOM: 5px; PADDING-TOP: 5px" align="middle"><span style="font-family: Arial;"><span style="font-size: 9pt;"> <a href="/index.php?main_page=product_info&amp;products_id=2184">9.7 inch 1024*768 Capacitive Multi-Touch Screen Android 2.2 UMPC with Freescale Cortex A8 CPU + HDMI + 3G Support</a></span></span></td>
</tr>
<tr style="FONT: bold 12px Verdana, Arial, Helvetica, sans-serif; COLOR: #bf0000">
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" width="25%" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;">Price: US$179.90</span></strong></td>
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" width="25%" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;"><span style="color: #800000;">Price: </span><span style="font-size: x-small; color: #800000;"><span style="text-decoration: line-through;">US$135.58</span></span> US$129.99<br /></span></strong></td>
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" width="25%" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;">Price: US$169.90</span></strong></td>
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" height="22" align="center"><strong><span style="font-size: small; font-family: Arial; color: #ff3300;">Price: US$319.35</span></strong></td>
</tr>
<tr style="FONT: bold 12px Verdana, Arial, Helvetica, sans-serif; COLOR: #bf0000">
<td style="FONT: bold 16px Arial, Helvetica, sans-serif; COLOR: #bf0000" colspan="4" height="50" align="center" valign="bottom"><a href="/index.php?main_page=index&amp;cPath=1132" target="_blank"> <img src="/images/e-dm/apad-ad-bottom.gif" border="0" alt="Wholesale Android Tablet PC ebook netbook from Chinajiaho" width="735" height="45" align="absbottom" /></a></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>